PANDOC ?= /opt/homebrew/bin/pandoc
PDF_ENGINE ?= /opt/homebrew/bin/tectonic
OUT_DIR := dist

# Book order: cover + chapters. TOC is auto-generated by pandoc so links always stay correct.
BOOK_FILES := "Cover page.md" \
	"Chapter 1.md" "Chapter 2.md" "Chapter 3.md" \
	"Chapter 21.md" "Chapter 22.md" "Chapter 23.md" "Chapter 24.md" \
	"Chapter 25.md" "Chapter 26.md" "Chapter 27.md" \
	"Chapter 4.md" "Chapter 5.md" "Chapter 6.md" "Chapter 7.md" \
	"Chapter 8.md" "Chapter 9.md" "Chapter 10.md" "Chapter 11.md" \
	"Chapter 12.md" "Chapter 13.md" "Chapter 14.md" "Chapter 15.md" \
	"Chapter 16.md" "Chapter 17.md" "Chapter 18.md" "Chapter 19.md" \
	"Chapter 20.md"

PDF := $(OUT_DIR)/engineering-ai-print-edition.pdf
EPUB := $(OUT_DIR)/engineering-ai-ereader.epub
HTML := $(OUT_DIR)/engineering-ai.html

PANDOC_COMMON := --metadata-file=metadata.yaml --toc --toc-depth=1 --number-sections

.PHONY: all pdf epub html clean dist

all: dist pdf epub html

dist:
	mkdir -p $(OUT_DIR)

pdf: dist
	$(PANDOC) $(BOOK_FILES) -o $(PDF) \
		$(PANDOC_COMMON) \
		--pdf-engine=$(PDF_ENGINE) \
		--standalone \
		--top-level-division=chapter

epub: dist
	$(PANDOC) $(BOOK_FILES) -o $(EPUB) \
		$(PANDOC_COMMON) \
		--standalone \
		--css=styles.css

html: dist
	$(PANDOC) $(BOOK_FILES) -o $(HTML) \
		$(PANDOC_COMMON) \
		--standalone \
		--section-divs \
		--css=styles.css

clean:
	rm -f $(PDF) $(EPUB) $(HTML)
